name: test

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - master

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get PR approval
        id: pr
        run: |
          echo "::set-output name=approval::true"
          echo "::set-output name=message::This pull request looks good."
      - uses: ./
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          pr-approval: "${{ steps.pr.outputs.approval }}"
          pr-message: "${{ steps.pr.outputs.message }}"
